#!/bin/sh

DOCKER_IMAGE=chriss-weight-tracker:latest

function ensure_docker_image_exists() {
  if ! docker image inspect $DOCKER_IMAGE &>/dev/null; then
    echo "docker image does not exist: run ./setup"
    exit 1
  fi
}

if [ -z "$FITBIT_CLIENT_ID" ] ; then
  echo "FITBIT_CLIENT_ID is unset, unable to continue"
  exit 1
fi

if [ -z "$FITBIT_CLIENT_SECRET" ] ; then
  echo "FITBIT_CLIENT_SECRET is unset, unable to continue"
  exit 1
fi

ensure_docker_image_exists
docker run --rm -it --mount type=bind,source="$(pwd)",destination=/workspace -e FITBIT_CLIENT_ID=$FITBIT_CLIENT_ID -e FITBIT_CLIENT_SECRET=$FITBIT_CLIENT_SECRET -e FITBIT_DATABASE=/workspace/fitbit.sqlite $DOCKER_IMAGE /workspace/Weight_Tracker.tsv
