apiVersion: batch/v1
kind: CronJob
metadata:
  name: '{{ include "chriss-weight-tracker.fullname" . }}-scheduled-job'
  labels:
    {{- include "chriss-weight-tracker.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronSchedule }}"
  timeZone: "{{ .Values.cronTimeZone }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "chriss-weight-tracker.selectorLabels" . | nindent 12 }}
          annotations:
            {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- include "chriss-weight-tracker.podSpec" . | nindent 10 }}
