apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chriss-weight-tracker.fullname" . }}
  labels:
    {{- include "chriss-weight-tracker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chriss-weight-tracker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chriss-weight-tracker.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "chriss-weight-tracker.podSpec" . | nindent 6 }}
