height: 183
googleSheetUrl: https://docs.google.com/spreadsheets/d/1kuox8iG8QNvHe26b8bTtmaRNcCG1lDVoTH84GKkMu5M/edit?gid=0

fitbitSecretName: chris-fitbit

ingress:
  hostname: chris.weight-tracker.omelette.gay
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: "kube-system-redirect-https@kubernetescrd"
  tls:
    - hosts:
        - chris.weight-tracker.omelette.gay
      secretName: chris-ingress-tls
